"""Sample dataset for the CliniData AI demo - the single source of truth that
`seed.py` loads into Postgres, Neo4j and Pinecone.

The organisation ("Meridian Clinical Research") is fictional. Obligation texts
are short paraphrases of the cited provisions for demonstration only - they are
not legal advice and not a substitute for the official text.

Gaps are left in on purpose so the demo has something to find, e.g. a breach
procedure that meets HIPAA's 60-day window but not GDPR's or DPDP's 72 hours.
"""

H = 24  # hours per day

REGULATIONS = [
    {"id": "REG-HIPAA-SEC", "name": "HIPAA Security Rule", "framework": "HIPAA", "jurisdiction": "US",
     "version": "45 CFR Part 164 Subpart C", "effective_date": "2005-04-20",
     "source_url": "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-C"},
    {"id": "REG-HIPAA-PRV", "name": "HIPAA Privacy & Breach Notification Rules", "framework": "HIPAA",
     "jurisdiction": "US", "version": "45 CFR Part 164 Subparts D-E", "effective_date": "2009-09-23",
     "source_url": "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164"},
    {"id": "REG-GDPR", "name": "General Data Protection Regulation (health data)", "framework": "GDPR",
     "jurisdiction": "EU", "version": "Regulation (EU) 2016/679", "effective_date": "2018-05-25",
     "source_url": "https://eur-lex.europa.eu/eli/reg/2016/679/oj"},
    {"id": "REG-CFR11", "name": "21 CFR Part 11 - Electronic Records; Electronic Signatures",
     "framework": "21 CFR Part 11", "jurisdiction": "US", "version": "21 CFR Part 11",
     "effective_date": "1997-08-20", "source_url": "https://www.ecfr.gov/current/title-21/chapter-I/subchapter-A/part-11"},
    {"id": "REG-ICH-E6", "name": "ICH E6(R3) Good Clinical Practice", "framework": "ICH GCP",
     "jurisdiction": "International", "version": "E6(R3)", "effective_date": "2025-07-23",
     "source_url": "https://database.ich.org/sites/default/files/ICH_E6%28R3%29_Step4_FinalGuideline_2025_0106.pdf"},
    {"id": "REG-ICH-E2A", "name": "ICH E2A Clinical Safety Data Management", "framework": "ICH GCP",
     "jurisdiction": "International", "version": "E2A", "effective_date": "1994-10-27",
     "source_url": "https://database.ich.org/sites/default/files/E2A_Guideline.pdf"},
    {"id": "REG-DPDP", "name": "Digital Personal Data Protection Act 2023", "framework": "DPDP",
     "jurisdiction": "India", "version": "Act No. 22 of 2023 + DPDP Rules 2025", "effective_date": "2025-11-13",
     "source_url": "https://www.meity.gov.in/data-protection-framework"},
    {"id": "REG-ISO27001", "name": "ISO/IEC 27001:2022 Annex A", "framework": "ISO 27001",
     "jurisdiction": "International", "version": "2022", "effective_date": "2022-10-25",
     "source_url": "https://www.iso.org/standard/27001"},
]

# deadline_hours = the maximum time the obligation allows (used by the constraint verifier)
OBLIGATIONS = [
    # --- HIPAA Security Rule -------------------------------------------------
    {"id": "OBL-HIPAA-RA", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.308(a)(1)(ii)(A)",
     "title": "Security risk analysis",
     "text": "Conduct an accurate and thorough assessment of the potential risks and vulnerabilities to the confidentiality, integrity and availability of electronic protected health information (ePHI).",
     "obligation_type": "administrative", "severity": "CRITICAL"},
    {"id": "OBL-HIPAA-TRAIN", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.308(a)(5)",
     "title": "Security awareness and training",
     "text": "Implement a security awareness and training program for all members of the workforce, including management.",
     "obligation_type": "administrative", "severity": "MEDIUM"},
    {"id": "OBL-HIPAA-INCIDENT", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.308(a)(6)",
     "title": "Security incident procedures",
     "text": "Identify and respond to suspected or known security incidents, mitigate harmful effects to the extent practicable, and document incidents and their outcomes.",
     "obligation_type": "administrative", "severity": "HIGH"},
    {"id": "OBL-HIPAA-CONTINGENCY", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.308(a)(7)",
     "title": "Contingency plan: data backup and disaster recovery",
     "text": "Establish a data backup plan to create and maintain retrievable exact copies of ePHI, a disaster recovery plan to restore any loss of data, and periodic testing and revision procedures.",
     "obligation_type": "administrative", "severity": "HIGH"},
    {"id": "OBL-HIPAA-BAA", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.308(b)",
     "title": "Business associate contracts",
     "text": "Permit a business associate to create, receive, maintain or transmit ePHI only with satisfactory written assurances that it will appropriately safeguard the information.",
     "obligation_type": "administrative", "severity": "HIGH"},
    {"id": "OBL-HIPAA-312A1", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.312(a)(1)",
     "title": "Access control: unique user identification",
     "text": "Implement technical policies and procedures that allow access to ePHI only to authorized persons or software programs, including a unique name or number for identifying and tracking each user.",
     "obligation_type": "technical", "severity": "CRITICAL"},
    {"id": "OBL-HIPAA-312A2III", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.312(a)(2)(iii)",
     "title": "Automatic logoff",
     "text": "Implement electronic procedures that terminate an electronic session after a predetermined time of inactivity (addressable).",
     "obligation_type": "technical", "severity": "MEDIUM"},
    {"id": "OBL-HIPAA-312A2IV", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.312(a)(2)(iv)",
     "title": "Encryption and decryption of ePHI",
     "text": "Implement a mechanism to encrypt and decrypt electronic protected health information (addressable), including ePHI stored on workstations and portable devices.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-HIPAA-312B", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.312(b)",
     "title": "Audit controls",
     "text": "Implement hardware, software and procedural mechanisms that record and examine activity in information systems that contain or use ePHI.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-HIPAA-312C", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.312(c)(1)",
     "title": "Integrity of ePHI",
     "text": "Implement policies and procedures to protect ePHI from improper alteration or destruction.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-HIPAA-312D", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.312(d)",
     "title": "Person or entity authentication",
     "text": "Implement procedures to verify that a person or entity seeking access to ePHI is the one claimed.",
     "obligation_type": "technical", "severity": "CRITICAL"},
    {"id": "OBL-HIPAA-312E", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.312(e)(1)",
     "title": "Transmission security",
     "text": "Implement technical security measures to guard against unauthorized access to ePHI being transmitted over an electronic communications network, including encryption where appropriate.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-HIPAA-DOCS", "regulation_id": "REG-HIPAA-SEC", "article_ref": "§164.316(b)(2)",
     "title": "Documentation retention (6 years)",
     "text": "Retain required security policies, procedures and documentation for 6 years from the date of creation or the date when last in effect, whichever is later.",
     "obligation_type": "documentation", "severity": "MEDIUM"},
    # --- HIPAA Privacy & Breach Notification --------------------------------
    {"id": "OBL-HIPAA-BN-IND", "regulation_id": "REG-HIPAA-PRV", "article_ref": "§164.404",
     "title": "Breach notification to individuals",
     "text": "Notify each affected individual of a breach of unsecured PHI without unreasonable delay and in no case later than 60 calendar days after discovery of the breach.",
     "obligation_type": "reporting", "severity": "CRITICAL", "deadline_hours": 60 * H, "deadline_label": "60 calendar days"},
    {"id": "OBL-HIPAA-BN-HHS", "regulation_id": "REG-HIPAA-PRV", "article_ref": "§164.408",
     "title": "Breach notification to HHS",
     "text": "Notify the Secretary of HHS of breaches of unsecured PHI; breaches affecting 500 or more individuals must be reported contemporaneously with individual notice (within 60 days).",
     "obligation_type": "reporting", "severity": "HIGH", "deadline_hours": 60 * H, "deadline_label": "60 calendar days"},
    {"id": "OBL-HIPAA-MIN", "regulation_id": "REG-HIPAA-PRV", "article_ref": "§164.502(b)",
     "title": "Minimum necessary",
     "text": "Make reasonable efforts to limit uses and disclosures of PHI to the minimum necessary to accomplish the intended purpose.",
     "obligation_type": "administrative", "severity": "MEDIUM"},
    {"id": "OBL-HIPAA-ACCESS", "regulation_id": "REG-HIPAA-PRV", "article_ref": "§164.524",
     "title": "Individual right of access",
     "text": "Act on an individual's request for access to their PHI no later than 30 days after receipt (one 30-day extension permitted with written notice).",
     "obligation_type": "reporting", "severity": "HIGH", "deadline_hours": 30 * H, "deadline_label": "30 days"},
    # --- GDPR -----------------------------------------------------------------
    {"id": "OBL-GDPR-9", "regulation_id": "REG-GDPR", "article_ref": "Art. 9",
     "title": "Lawful basis for health data",
     "text": "Processing of data concerning health is prohibited unless an Article 9(2) condition applies, such as explicit consent or scientific research with appropriate safeguards.",
     "obligation_type": "administrative", "severity": "CRITICAL"},
    {"id": "OBL-GDPR-15", "regulation_id": "REG-GDPR", "article_ref": "Art. 15 / Art. 12(3)",
     "title": "Data subject right of access",
     "text": "Provide the data subject with a copy of their personal data and information on the processing without undue delay and within one month of receipt of the request (extendable by two further months for complex requests).",
     "obligation_type": "reporting", "severity": "HIGH", "deadline_hours": 30 * H, "deadline_label": "one month"},
    {"id": "OBL-GDPR-28", "regulation_id": "REG-GDPR", "article_ref": "Art. 28",
     "title": "Processor contracts",
     "text": "Use only processors providing sufficient guarantees, bound by a written contract setting out the subject matter, duration, nature and purpose of the processing and the processor's security obligations.",
     "obligation_type": "administrative", "severity": "HIGH"},
    {"id": "OBL-GDPR-32", "regulation_id": "REG-GDPR", "article_ref": "Art. 32",
     "title": "Security of processing",
     "text": "Implement appropriate technical and organisational measures, including pseudonymisation and encryption, ongoing confidentiality, integrity, availability and resilience, timely restoration of access, and regular testing of effectiveness.",
     "obligation_type": "technical", "severity": "CRITICAL"},
    {"id": "OBL-GDPR-33", "regulation_id": "REG-GDPR", "article_ref": "Art. 33",
     "title": "Breach notification to the supervisory authority",
     "text": "Notify a personal data breach to the competent supervisory authority without undue delay and, where feasible, not later than 72 hours after becoming aware of it.",
     "obligation_type": "reporting", "severity": "CRITICAL", "deadline_hours": 72, "deadline_label": "72 hours"},
    {"id": "OBL-GDPR-35", "regulation_id": "REG-GDPR", "article_ref": "Art. 35",
     "title": "Data protection impact assessment",
     "text": "Carry out a DPIA before processing likely to result in a high risk, including large-scale processing of special categories of data such as health data in clinical trials.",
     "obligation_type": "documentation", "severity": "HIGH"},
    {"id": "OBL-GDPR-37", "regulation_id": "REG-GDPR", "article_ref": "Art. 37",
     "title": "Designation of a data protection officer",
     "text": "Designate a DPO where core activities consist of large-scale processing of special categories of data.",
     "obligation_type": "administrative", "severity": "MEDIUM"},
    # --- 21 CFR Part 11 -------------------------------------------------------
    {"id": "OBL-P11-VAL", "regulation_id": "REG-CFR11", "article_ref": "§11.10(a)",
     "title": "System validation",
     "text": "Validate systems to ensure accuracy, reliability, consistent intended performance, and the ability to discern invalid or altered records.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-P11-RETAIN", "regulation_id": "REG-CFR11", "article_ref": "§11.10(c)",
     "title": "Record protection and retention",
     "text": "Protect records to enable their accurate and ready retrieval throughout the records retention period.",
     "obligation_type": "documentation", "severity": "MEDIUM"},
    {"id": "OBL-P11-ACCESS", "regulation_id": "REG-CFR11", "article_ref": "§11.10(d)",
     "title": "Limit system access",
     "text": "Limit system access to authorized individuals.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-P11-AUDIT", "regulation_id": "REG-CFR11", "article_ref": "§11.10(e)",
     "title": "Secure, time-stamped audit trails",
     "text": "Use secure, computer-generated, time-stamped audit trails to independently record the date and time of operator entries and actions that create, modify or delete electronic records; changes must not obscure previously recorded information, and audit trails must be retained at least as long as the records.",
     "obligation_type": "technical", "severity": "CRITICAL"},
    {"id": "OBL-P11-TRAIN", "regulation_id": "REG-CFR11", "article_ref": "§11.10(i)",
     "title": "Training of system users",
     "text": "Determine that persons who develop, maintain or use electronic record/electronic signature systems have the education, training and experience to perform their assigned tasks.",
     "obligation_type": "administrative", "severity": "MEDIUM"},
    {"id": "OBL-P11-ESIG", "regulation_id": "REG-CFR11", "article_ref": "§11.200(a)",
     "title": "Electronic signature components",
     "text": "Electronic signatures not based on biometrics must employ at least two distinct identification components, such as an identification code and password.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-P11-PWD", "regulation_id": "REG-CFR11", "article_ref": "§11.300",
     "title": "Controls for identification codes and passwords",
     "text": "Maintain the uniqueness of ID code and password combinations, periodically check and revise them, and follow loss-management procedures for compromised credentials or devices.",
     "obligation_type": "technical", "severity": "HIGH"},
    # --- ICH E6(R3) -----------------------------------------------------------
    {"id": "OBL-GCP-QM", "regulation_id": "REG-ICH-E6", "article_ref": "E6(R3) Sponsor: quality management",
     "title": "Risk-proportionate quality management",
     "text": "The sponsor should implement a risk-proportionate quality management system that identifies factors critical to quality and manages risks to participant safety and the reliability of trial results.",
     "obligation_type": "administrative", "severity": "HIGH"},
    {"id": "OBL-GCP-CSV", "regulation_id": "REG-ICH-E6", "article_ref": "E6(R3) Data governance: computerised systems",
     "title": "Computerised systems fit for purpose",
     "text": "Computerised systems used in the trial should be validated in a risk-based manner, with audit trails, access controls and data backup appropriate to their impact on participant safety and data reliability.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-GCP-RECORDS", "regulation_id": "REG-ICH-E6", "article_ref": "E6(R3) Essential records",
     "title": "Retention of essential records",
     "text": "Essential records should be retained securely and remain accessible for the period required by applicable regulatory requirements.",
     "obligation_type": "documentation", "severity": "MEDIUM"},
    # --- ICH E2A (pharmacovigilance) ----------------------------------------
    {"id": "OBL-E2A-FATAL", "regulation_id": "REG-ICH-E2A", "article_ref": "E2A III.A.1",
     "title": "Expedited report: fatal or life-threatening SUSARs",
     "text": "Fatal or life-threatening unexpected adverse drug reactions must be reported to regulators as soon as possible and no later than 7 calendar days after first knowledge, followed by a complete report within 8 additional days.",
     "obligation_type": "reporting", "severity": "CRITICAL", "deadline_hours": 7 * H, "deadline_label": "7 calendar days"},
    {"id": "OBL-E2A-OTHER", "regulation_id": "REG-ICH-E2A", "article_ref": "E2A III.A.2",
     "title": "Expedited report: other serious unexpected ADRs",
     "text": "Serious, unexpected adverse drug reactions that are not fatal or life-threatening must be reported as soon as possible and no later than 15 calendar days after first knowledge.",
     "obligation_type": "reporting", "severity": "HIGH", "deadline_hours": 15 * H, "deadline_label": "15 calendar days"},
    # --- DPDP Act 2023 --------------------------------------------------------
    {"id": "OBL-DPDP-6", "regulation_id": "REG-DPDP", "article_ref": "Section 6",
     "title": "Free, specific, informed consent",
     "text": "Process personal data only on consent that is free, specific, informed, unconditional and unambiguous, with a clear affirmative action, and allow withdrawal as easily as it was given.",
     "obligation_type": "administrative", "severity": "HIGH"},
    {"id": "OBL-DPDP-8-5", "regulation_id": "REG-DPDP", "article_ref": "Section 8(5)",
     "title": "Reasonable security safeguards",
     "text": "Protect personal data in possession or under control by taking reasonable security safeguards to prevent a personal data breach, including encryption, access control and logging.",
     "obligation_type": "technical", "severity": "CRITICAL"},
    {"id": "OBL-DPDP-8-6", "regulation_id": "REG-DPDP", "article_ref": "Section 8(6) + DPDP Rules 2025",
     "title": "Breach intimation to the Board and Data Principals",
     "text": "Intimate each affected Data Principal of a personal data breach without delay and furnish a detailed report to the Data Protection Board within 72 hours of becoming aware of it.",
     "obligation_type": "reporting", "severity": "CRITICAL", "deadline_hours": 72, "deadline_label": "72 hours"},
    {"id": "OBL-DPDP-9", "regulation_id": "REG-DPDP", "article_ref": "Section 9",
     "title": "Verifiable parental consent for children's data",
     "text": "Obtain verifiable consent of the parent or lawful guardian before processing personal data of a child, and do not undertake tracking or behavioural monitoring of children.",
     "obligation_type": "administrative", "severity": "HIGH"},
    {"id": "OBL-DPDP-11", "regulation_id": "REG-DPDP", "article_ref": "Section 11",
     "title": "Right to access information",
     "text": "Provide a Data Principal, on request, a summary of the personal data being processed and the processing activities undertaken.",
     "obligation_type": "reporting", "severity": "MEDIUM"},
    # --- ISO 27001:2022 Annex A ---------------------------------------------
    {"id": "OBL-ISO-515", "regulation_id": "REG-ISO27001", "article_ref": "A.5.15",
     "title": "Access control policy",
     "text": "Rules to control physical and logical access to information and assets shall be established and implemented based on business and security requirements.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-ISO-519", "regulation_id": "REG-ISO27001", "article_ref": "A.5.19",
     "title": "Information security in supplier relationships",
     "text": "Processes shall be defined to manage the information security risks associated with the use of suppliers' products or services.",
     "obligation_type": "administrative", "severity": "MEDIUM"},
    {"id": "OBL-ISO-526", "regulation_id": "REG-ISO27001", "article_ref": "A.5.26",
     "title": "Response to information security incidents",
     "text": "Information security incidents shall be responded to in accordance with documented procedures.",
     "obligation_type": "administrative", "severity": "HIGH"},
    {"id": "OBL-ISO-85", "regulation_id": "REG-ISO27001", "article_ref": "A.8.5",
     "title": "Secure authentication",
     "text": "Secure authentication technologies and procedures shall be implemented based on access restrictions and the topic-specific policy on access control.",
     "obligation_type": "technical", "severity": "HIGH"},
    {"id": "OBL-ISO-813", "regulation_id": "REG-ISO27001", "article_ref": "A.8.13",
     "title": "Information backup",
     "text": "Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed backup policy.",
     "obligation_type": "technical", "severity": "MEDIUM"},
    {"id": "OBL-ISO-815", "regulation_id": "REG-ISO27001", "article_ref": "A.8.15",
     "title": "Logging",
     "text": "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.",
     "obligation_type": "technical", "severity": "MEDIUM"},
    {"id": "OBL-ISO-824", "regulation_id": "REG-ISO27001", "article_ref": "A.8.24",
     "title": "Use of cryptography",
     "text": "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.",
     "obligation_type": "technical", "severity": "HIGH"},
]

# Cross-framework equivalences (MAPS_TO). Stored one way, traversed both ways.
MAPPINGS = [
    ("OBL-HIPAA-BN-IND", "OBL-GDPR-33", "Breach notification"),
    ("OBL-HIPAA-BN-IND", "OBL-DPDP-8-6", "Breach notification"),
    ("OBL-GDPR-33", "OBL-DPDP-8-6", "Breach notification"),
    ("OBL-HIPAA-INCIDENT", "OBL-ISO-526", "Incident response"),
    ("OBL-HIPAA-312A2IV", "OBL-GDPR-32", "Encryption of health data"),
    ("OBL-HIPAA-312A2IV", "OBL-ISO-824", "Encryption of health data"),
    ("OBL-DPDP-8-5", "OBL-GDPR-32", "Security safeguards"),
    ("OBL-HIPAA-312B", "OBL-P11-AUDIT", "Audit trails"),
    ("OBL-HIPAA-312B", "OBL-ISO-815", "Audit logging"),
    ("OBL-HIPAA-312D", "OBL-P11-PWD", "Authentication"),
    ("OBL-HIPAA-312D", "OBL-ISO-85", "Authentication"),
    ("OBL-HIPAA-312A1", "OBL-P11-ACCESS", "Access control"),
    ("OBL-HIPAA-312A1", "OBL-ISO-515", "Access control"),
    ("OBL-HIPAA-CONTINGENCY", "OBL-ISO-813", "Backup"),
    ("OBL-HIPAA-BAA", "OBL-GDPR-28", "Third-party processors"),
    ("OBL-GDPR-28", "OBL-ISO-519", "Third-party processors"),
    ("OBL-HIPAA-ACCESS", "OBL-GDPR-15", "Right of access"),
    ("OBL-GDPR-15", "OBL-DPDP-11", "Right of access"),
    ("OBL-HIPAA-DOCS", "OBL-P11-RETAIN", "Record retention"),
    ("OBL-P11-RETAIN", "OBL-GCP-RECORDS", "Record retention"),
    ("OBL-P11-VAL", "OBL-GCP-CSV", "Computerised system validation"),
    ("OBL-HIPAA-TRAIN", "OBL-P11-TRAIN", "Workforce training"),
    ("OBL-GDPR-9", "OBL-DPDP-6", "Consent for health data"),
]

ENTITIES = [
    {"id": "ENT-MERIDIAN", "name": "Meridian Clinical Research (fictional)", "entity_type": "legal_entity", "jurisdiction": "US / EU / India"},
    {"id": "ENT-IT", "name": "IT Security", "entity_type": "department", "jurisdiction": None},
    {"id": "ENT-PRIVACY", "name": "Privacy Office / DPO", "entity_type": "department", "jurisdiction": None},
    {"id": "ENT-QA", "name": "Quality Assurance (GxP)", "entity_type": "department", "jurisdiction": None},
    {"id": "ENT-PV", "name": "Drug Safety & Pharmacovigilance", "entity_type": "department", "jurisdiction": None},
    {"id": "ENT-CLINOPS", "name": "Clinical Operations", "entity_type": "department", "jurisdiction": None},
    {"id": "ENT-CRO", "name": "Northbridge CRO (fictional vendor)", "entity_type": "third_party", "jurisdiction": "EU"},
]

ASSETS = [
    {"id": "AST-EHR", "name": "Electronic Health Record platform", "asset_type": "system", "classification": "restricted_phi", "owner_id": "ENT-IT", "location": "us-east-1"},
    {"id": "AST-EDC", "name": "Electronic Data Capture (EDC) system", "asset_type": "system", "classification": "restricted_phi", "owner_id": "ENT-CLINOPS", "location": "eu-central-1"},
    {"id": "AST-ETMF", "name": "Electronic Trial Master File (eTMF)", "asset_type": "data_store", "classification": "confidential", "owner_id": "ENT-QA", "location": "eu-central-1"},
    {"id": "AST-SAFETY", "name": "Pharmacovigilance safety database", "asset_type": "data_store", "classification": "restricted_phi", "owner_id": "ENT-PV", "location": "us-east-1"},
    {"id": "AST-LAPTOP", "name": "Clinician and CRA laptop fleet", "asset_type": "device", "classification": "restricted_phi", "owner_id": "ENT-IT", "location": "field"},
    {"id": "AST-PORTAL", "name": "Patient & participant portal", "asset_type": "system", "classification": "restricted_phi", "owner_id": "ENT-CLINOPS", "location": "ap-south-1"},
    {"id": "AST-DWH", "name": "Clinical data warehouse", "asset_type": "data_store", "classification": "restricted_phi", "owner_id": "ENT-IT", "location": "us-east-1"},
    {"id": "AST-IDP", "name": "Identity provider (SSO/MFA)", "asset_type": "system", "classification": "confidential", "owner_id": "ENT-IT", "location": "global"},
    {"id": "AST-BACKUP", "name": "Encrypted backup vault", "asset_type": "data_store", "classification": "restricted_phi", "owner_id": "ENT-IT", "location": "us-west-2"},
    {"id": "AST-CRO", "name": "Northbridge CRO monitoring services", "asset_type": "third_party", "classification": "confidential", "owner_id": "ENT-CLINOPS", "location": "EU"},
]

# sla_hours = what the control commits to (compared against obligation deadline_hours)
CONTROLS = [
    {"id": "CTL-RA-01", "name": "Annual enterprise security risk analysis",
     "description": "Enterprise-wide HIPAA risk analysis covering all systems that store or process ePHI. Last completed assessment expired; the 2025 cycle was not performed.",
     "control_type": "administrative", "owner_id": "ENT-IT", "implementation_status": "failed", "effectiveness": 0.20,
     "last_assessed": "2024-03-15", "satisfies": ["OBL-HIPAA-RA", "OBL-GCP-QM"], "assets": ["AST-EHR", "AST-EDC", "AST-DWH"]},
    {"id": "CTL-TRAIN-01", "name": "Security & GxP awareness training",
     "description": "Annual security awareness and Part 11 system-user training with completion tracking in the LMS; new hires complete it within 30 days.",
     "control_type": "administrative", "owner_id": "ENT-QA", "implementation_status": "implemented", "effectiveness": 0.85,
     "last_assessed": "2026-02-01", "satisfies": ["OBL-HIPAA-TRAIN", "OBL-P11-TRAIN"], "assets": []},
    {"id": "CTL-IR-01", "name": "Incident response & breach notification procedure",
     "description": "SOP-SEC-014 defines incident triage, containment, and breach notification. Notification to regulators and affected individuals is committed within 30 days of breach discovery.",
     "control_type": "procedural", "owner_id": "ENT-PRIVACY", "implementation_status": "implemented", "effectiveness": 0.75,
     "sla_hours": 30 * H, "last_assessed": "2026-01-20",
     "satisfies": ["OBL-HIPAA-INCIDENT", "OBL-HIPAA-BN-IND", "OBL-HIPAA-BN-HHS", "OBL-GDPR-33", "OBL-DPDP-8-6", "OBL-ISO-526"],
     "assets": ["AST-EHR", "AST-EDC", "AST-PORTAL"]},
    {"id": "CTL-BCK-01", "name": "Encrypted nightly backups",
     "description": "Nightly encrypted snapshots of EHR, EDC and safety database replicated to a separate region with 35-day retention.",
     "control_type": "technical", "owner_id": "ENT-IT", "implementation_status": "implemented", "effectiveness": 0.90,
     "last_assessed": "2026-03-10", "satisfies": ["OBL-HIPAA-CONTINGENCY", "OBL-ISO-813"], "assets": ["AST-BACKUP", "AST-EHR", "AST-EDC", "AST-SAFETY"]},
    {"id": "CTL-DR-01", "name": "Disaster recovery testing",
     "description": "Semi-annual restore test of critical clinical systems against RTO/RPO targets. First full test is scheduled but not yet executed.",
     "control_type": "procedural", "owner_id": "ENT-IT", "implementation_status": "in_progress", "effectiveness": 0.30,
     "last_assessed": None, "satisfies": ["OBL-HIPAA-CONTINGENCY"], "assets": ["AST-BACKUP"]},
    {"id": "CTL-VEND-01", "name": "Business associate & processor agreements",
     "description": "Standard BAA and GDPR Article 28 data processing agreement executed with every vendor handling PHI, reviewed annually by Legal.",
     "control_type": "administrative", "owner_id": "ENT-PRIVACY", "implementation_status": "implemented", "effectiveness": 0.80,
     "last_assessed": "2025-11-05", "satisfies": ["OBL-HIPAA-BAA", "OBL-GDPR-28", "OBL-ISO-519"], "assets": ["AST-CRO"]},
    {"id": "CTL-IAM-01", "name": "Centralised identity and role-based access",
     "description": "All clinical systems federate to the SSO identity provider; unique user IDs, role-based access profiles and quarterly access recertification.",
     "control_type": "technical", "owner_id": "ENT-IT", "implementation_status": "implemented", "effectiveness": 0.85,
     "last_assessed": "2026-04-02", "satisfies": ["OBL-HIPAA-312A1", "OBL-P11-ACCESS", "OBL-ISO-515", "OBL-HIPAA-MIN"],
     "assets": ["AST-IDP", "AST-EHR", "AST-EDC", "AST-ETMF"]},
    {"id": "CTL-MFA-01", "name": "Multi-factor authentication",
     "description": "Phishing-resistant MFA enforced at the identity provider for all workforce and CRO accounts accessing PHI.",
     "control_type": "technical", "owner_id": "ENT-IT", "implementation_status": "implemented", "effectiveness": 0.90,
     "last_assessed": "2026-04-02", "satisfies": ["OBL-HIPAA-312D", "OBL-ISO-85", "OBL-P11-PWD"], "assets": ["AST-IDP"]},
    {"id": "CTL-ENC-01", "name": "Database encryption at rest",
     "description": "AES-256 encryption at rest with KMS-managed keys for the EHR, EDC, safety database and data warehouse.",
     "control_type": "technical", "owner_id": "ENT-IT", "implementation_status": "implemented", "effectiveness": 0.90,
     "last_assessed": "2026-03-10", "satisfies": ["OBL-HIPAA-312A2IV", "OBL-GDPR-32", "OBL-ISO-824", "OBL-DPDP-8-5"],
     "assets": ["AST-EHR", "AST-EDC", "AST-SAFETY", "AST-DWH"]},
    {"id": "CTL-ENC-02", "name": "Laptop full-disk encryption",
     "description": "Rollout of full-disk encryption to clinician and CRA laptops. 62% of the fleet enrolled; field devices outstanding.",
     "control_type": "technical", "owner_id": "ENT-IT", "implementation_status": "in_progress", "effectiveness": 0.40,
     "last_assessed": "2026-05-12", "satisfies": ["OBL-HIPAA-312A2IV"], "assets": ["AST-LAPTOP"]},
    {"id": "CTL-TLS-01", "name": "TLS 1.3 for data in transit",
     "description": "TLS 1.3 enforced at the edge and between services for all PHI transmission; legacy ciphers disabled.",
     "control_type": "technical", "owner_id": "ENT-IT", "implementation_status": "implemented", "effectiveness": 0.90,
     "last_assessed": "2026-03-10", "satisfies": ["OBL-HIPAA-312E"], "assets": ["AST-PORTAL", "AST-EHR"]},
    {"id": "CTL-LOG-01", "name": "Central security logging (SIEM)",
     "description": "Security event logs from the EHR, portal and identity provider streamed to the SIEM with 13-month retention and daily review of alerts.",
     "control_type": "technical", "owner_id": "ENT-IT", "implementation_status": "implemented", "effectiveness": 0.80,
     "last_assessed": "2026-02-18", "satisfies": ["OBL-HIPAA-312B", "OBL-ISO-815"], "assets": ["AST-EHR", "AST-PORTAL", "AST-IDP"]},
    {"id": "CTL-P11-AT", "name": "EDC Part 11 audit trail",
     "description": "The EDC system generates secure, time-stamped audit trails for create/modify/delete actions. Audit trail review is not yet documented and no evidence has been collected.",
     "control_type": "technical", "owner_id": "ENT-QA", "implementation_status": "implemented", "effectiveness": 0.60,
     "last_assessed": "2025-09-30", "satisfies": ["OBL-P11-AUDIT"], "assets": ["AST-EDC"]},
    {"id": "CTL-P11-ESIG", "name": "Two-component electronic signatures",
     "description": "EDC and eTMF e-signatures require user ID plus password re-entry and record printed name, date/time and signature meaning.",
     "control_type": "technical", "owner_id": "ENT-QA", "implementation_status": "implemented", "effectiveness": 0.85,
     "last_assessed": "2026-01-15", "satisfies": ["OBL-P11-ESIG"], "assets": ["AST-EDC", "AST-ETMF"]},
    {"id": "CTL-CSV-01", "name": "Computerised system validation programme",
     "description": "Risk-based CSV/CSA lifecycle for GxP systems. Validation packages complete for eTMF; EDC and safety database revalidation after the 2026 upgrade is in progress.",
     "control_type": "procedural", "owner_id": "ENT-QA", "implementation_status": "in_progress", "effectiveness": 0.50,
     "last_assessed": "2026-05-01", "satisfies": ["OBL-P11-VAL", "OBL-GCP-CSV"], "assets": ["AST-EDC", "AST-SAFETY", "AST-ETMF"]},
    {"id": "CTL-INTEG-01", "name": "Record integrity checks",
     "description": "Checksums and write-once storage protect clinical records and essential trial records against improper alteration.",
     "control_type": "technical", "owner_id": "ENT-QA", "implementation_status": "implemented", "effectiveness": 0.80,
     "last_assessed": "2026-02-10", "satisfies": ["OBL-HIPAA-312C", "OBL-P11-RETAIN"], "assets": ["AST-ETMF", "AST-EHR"]},
    {"id": "CTL-RET-01", "name": "Records retention schedule",
     "description": "Retention schedule keeps security documentation for 6 years and essential trial records for the longest applicable regulatory period.",
     "control_type": "administrative", "owner_id": "ENT-QA", "implementation_status": "implemented", "effectiveness": 0.85,
     "last_assessed": "2025-12-01", "satisfies": ["OBL-HIPAA-DOCS", "OBL-P11-RETAIN", "OBL-GCP-RECORDS"], "assets": ["AST-ETMF"]},
    {"id": "CTL-PV-01", "name": "Pharmacovigilance case processing SOP",
     "description": "SOP-PV-003 routes all serious unexpected adverse reaction cases to expedited submission within 15 calendar days of first knowledge; there is no separate 7-day track for fatal or life-threatening cases.",
     "control_type": "procedural", "owner_id": "ENT-PV", "implementation_status": "implemented", "effectiveness": 0.70,
     "sla_hours": 15 * H, "last_assessed": "2026-03-22", "satisfies": ["OBL-E2A-FATAL", "OBL-E2A-OTHER"], "assets": ["AST-SAFETY"]},
    {"id": "CTL-DSR-01", "name": "Data subject & patient access request process",
     "description": "Privacy Office handles patient HIPAA access requests and GDPR/DPDP data subject requests through a ticket queue with a 45-day service level.",
     "control_type": "procedural", "owner_id": "ENT-PRIVACY", "implementation_status": "implemented", "effectiveness": 0.65,
     "sla_hours": 45 * H, "last_assessed": "2026-01-08", "satisfies": ["OBL-HIPAA-ACCESS", "OBL-GDPR-15", "OBL-DPDP-11"], "assets": ["AST-PORTAL"]},
    {"id": "CTL-CONSENT-01", "name": "Electronic informed consent (eConsent)",
     "description": "eConsent captures explicit, granular consent for trial participation and secondary research use of health data, with withdrawal in the participant portal.",
     "control_type": "technical", "owner_id": "ENT-CLINOPS", "implementation_status": "implemented", "effectiveness": 0.85,
     "last_assessed": "2026-02-25", "satisfies": ["OBL-GDPR-9", "OBL-DPDP-6"], "assets": ["AST-PORTAL"]},
    {"id": "CTL-DPIA-01", "name": "DPIA programme for clinical studies",
     "description": "Template and workflow for data protection impact assessments on new studies. Approved by the DPO but not yet started for any active study.",
     "control_type": "administrative", "owner_id": "ENT-PRIVACY", "implementation_status": "not_started", "effectiveness": 0.0,
     "last_assessed": None, "satisfies": ["OBL-GDPR-35"], "assets": ["AST-EDC", "AST-DWH"]},
    {"id": "CTL-DPO-01", "name": "Designated DPO",
     "description": "A data protection officer is appointed and registered with the lead supervisory authority, reporting to the board.",
     "control_type": "administrative", "owner_id": "ENT-PRIVACY", "implementation_status": "implemented", "effectiveness": 0.90,
     "last_assessed": "2025-10-01", "satisfies": ["OBL-GDPR-37"], "assets": []},
    {"id": "CTL-QMS-01", "name": "Risk-based quality management for trials",
     "description": "Critical-to-quality factors identified per protocol with centralised monitoring; risk review cadence set per study.",
     "control_type": "procedural", "owner_id": "ENT-QA", "implementation_status": "in_progress", "effectiveness": 0.50,
     "last_assessed": "2026-04-18", "satisfies": ["OBL-GCP-QM"], "assets": ["AST-EDC", "AST-CRO"]},
]
# Deliberately uncovered: OBL-HIPAA-312A2III (automatic logoff), OBL-DPDP-9 (children's data)

EVIDENCE = [
    {"id": "EVD-001", "control_id": "CTL-TRAIN-01", "document_ref": "lms/exports/2026-training-completion.xlsx", "collected_at": "2026-02-01", "verified_by": "QA Lead"},
    {"id": "EVD-002", "control_id": "CTL-IR-01", "document_ref": "policies/SOP-SEC-014-incident-response-v4.pdf", "collected_at": "2026-01-20", "verified_by": "Privacy Officer"},
    {"id": "EVD-003", "control_id": "CTL-IR-01", "document_ref": "records/2025-tabletop-exercise-report.pdf", "collected_at": "2025-11-12", "verified_by": "CISO"},
    {"id": "EVD-004", "control_id": "CTL-BCK-01", "document_ref": "reports/backup-job-summary-2026-Q1.pdf", "collected_at": "2026-03-10", "verified_by": "IT Ops Manager"},
    {"id": "EVD-005", "control_id": "CTL-VEND-01", "document_ref": "contracts/northbridge-cro-baa-dpa-2025.pdf", "collected_at": "2025-11-05", "verified_by": "Legal Counsel"},
    {"id": "EVD-006", "control_id": "CTL-IAM-01", "document_ref": "reports/access-recertification-2026-Q1.csv", "collected_at": "2026-04-02", "verified_by": "IAM Lead"},
    {"id": "EVD-007", "control_id": "CTL-MFA-01", "document_ref": "screenshots/idp-mfa-policy-2026-04.png", "collected_at": "2026-04-02", "verified_by": "IAM Lead"},
    {"id": "EVD-008", "control_id": "CTL-ENC-01", "document_ref": "reports/kms-encryption-config-2026-03.json", "collected_at": "2026-03-10", "verified_by": "Cloud Security Engineer"},
    {"id": "EVD-009", "control_id": "CTL-TLS-01", "document_ref": "reports/tls-scan-2026-03.txt", "collected_at": "2026-03-10", "verified_by": "Cloud Security Engineer"},
    {"id": "EVD-010", "control_id": "CTL-LOG-01", "document_ref": "reports/siem-coverage-2026-02.pdf", "collected_at": "2026-02-18", "verified_by": "SOC Manager"},
    {"id": "EVD-011", "control_id": "CTL-P11-ESIG", "document_ref": "validation/edc-esignature-test-scripts.pdf", "collected_at": "2026-01-15", "verified_by": "CSV Specialist"},
    {"id": "EVD-012", "control_id": "CTL-INTEG-01", "document_ref": "reports/worm-storage-config-2026-02.pdf", "collected_at": "2026-02-10", "verified_by": "QA Lead"},
    {"id": "EVD-013", "control_id": "CTL-RET-01", "document_ref": "policies/records-retention-schedule-v7.pdf", "collected_at": "2025-12-01", "verified_by": "Records Manager"},
    {"id": "EVD-014", "control_id": "CTL-PV-01", "document_ref": "policies/SOP-PV-003-case-processing-v9.pdf", "collected_at": "2026-03-22", "verified_by": "QPPV"},
    {"id": "EVD-015", "control_id": "CTL-DSR-01", "document_ref": "reports/dsr-queue-metrics-2025-Q4.pdf", "collected_at": "2026-01-08", "verified_by": "Privacy Officer"},
    {"id": "EVD-016", "control_id": "CTL-CONSENT-01", "document_ref": "validation/econsent-uat-report.pdf", "collected_at": "2026-02-25", "verified_by": "Clinical Systems Lead"},
    {"id": "EVD-017", "control_id": "CTL-DPO-01", "document_ref": "records/dpo-registration-confirmation.pdf", "collected_at": "2025-10-01", "verified_by": "General Counsel"},
]
# Deliberately no evidence for CTL-P11-AT (implemented, but unevidenced)

RISKS = [
    {"id": "RSK-01", "name": "Delayed breach notification to EU/India regulators", "category": "regulatory", "likelihood": 4, "impact": 5, "asset_id": "AST-EDC",
     "threatens": ["OBL-GDPR-33", "OBL-DPDP-8-6"]},
    {"id": "RSK-02", "name": "Lost or stolen unencrypted laptop with PHI", "category": "security", "likelihood": 3, "impact": 4, "asset_id": "AST-LAPTOP",
     "threatens": ["OBL-HIPAA-312A2IV", "OBL-HIPAA-BN-IND"]},
    {"id": "RSK-03", "name": "Unassessed vulnerabilities in ePHI systems", "category": "security", "likelihood": 4, "impact": 4, "asset_id": "AST-EHR",
     "threatens": ["OBL-HIPAA-RA", "OBL-GDPR-32"]},
    {"id": "RSK-04", "name": "Late expedited reporting of fatal SUSARs", "category": "patient_safety", "likelihood": 3, "impact": 5, "asset_id": "AST-SAFETY",
     "threatens": ["OBL-E2A-FATAL"]},
    {"id": "RSK-05", "name": "Unreviewed EDC audit trail hides data manipulation", "category": "data_integrity", "likelihood": 2, "impact": 5, "asset_id": "AST-EDC",
     "threatens": ["OBL-P11-AUDIT", "OBL-HIPAA-312B"]},
    {"id": "RSK-06", "name": "Unattended sessions on shared clinic workstations", "category": "security", "likelihood": 3, "impact": 3, "asset_id": "AST-EHR",
     "threatens": ["OBL-HIPAA-312A2III"]},
    {"id": "RSK-07", "name": "Processing paediatric trial data without verified parental consent", "category": "regulatory", "likelihood": 3, "impact": 4, "asset_id": "AST-PORTAL",
     "threatens": ["OBL-DPDP-9"]},
    {"id": "RSK-08", "name": "Patient access requests answered after statutory deadline", "category": "regulatory", "likelihood": 4, "impact": 3, "asset_id": "AST-PORTAL",
     "threatens": ["OBL-HIPAA-ACCESS", "OBL-GDPR-15"]},
    {"id": "RSK-09", "name": "High-risk study processing without a DPIA", "category": "regulatory", "likelihood": 4, "impact": 3, "asset_id": "AST-DWH",
     "threatens": ["OBL-GDPR-35"]},
    {"id": "RSK-10", "name": "Unvalidated EDC upgrade affects data reliability", "category": "data_integrity", "likelihood": 3, "impact": 4, "asset_id": "AST-EDC",
     "threatens": ["OBL-P11-VAL", "OBL-GCP-CSV"]},
    {"id": "RSK-11", "name": "Failed restore during a ransomware event", "category": "availability", "likelihood": 2, "impact": 5, "asset_id": "AST-BACKUP",
     "threatens": ["OBL-HIPAA-CONTINGENCY", "OBL-ISO-813"]},
    {"id": "RSK-12", "name": "CRO mishandles trial participant data", "category": "third_party", "likelihood": 2, "impact": 4, "asset_id": "AST-CRO",
     "threatens": ["OBL-GDPR-28", "OBL-HIPAA-BAA"]},
]

# Internal policy excerpts - extra retrieval corpus linked to controls.
POLICY_CHUNKS = [
    {"id": "POL-001", "source_node_id": "CTL-IR-01", "framework": "Internal policy",
     "text": "SOP-SEC-014 section 6.2: Once a breach of personal or protected health information is confirmed, the Privacy Office notifies affected individuals and the relevant regulator within 30 days of discovery. Notification timelines are measured from the date the incident is classified as a breach."},
    {"id": "POL-002", "source_node_id": "CTL-PV-01", "framework": "Internal policy",
     "text": "SOP-PV-003 section 4.1: All serious unexpected suspected adverse reactions are submitted as expedited reports within 15 calendar days of first knowledge by any company personnel. Day 0 is the date the minimum criteria for a valid case are met."},
    {"id": "POL-003", "source_node_id": "CTL-DSR-01", "framework": "Internal policy",
     "text": "Privacy procedure PR-07: Requests from patients or research participants to access or receive a copy of their data are logged in the privacy queue and fulfilled within 45 days."},
    {"id": "POL-004", "source_node_id": "CTL-ENC-02", "framework": "Internal policy",
     "text": "Endpoint standard ES-02: Laptops that store or access PHI must use full-disk encryption. Devices enrolled before 2025 are being migrated; field CRA devices will be enrolled on their next refresh."},
    {"id": "POL-005", "source_node_id": "CTL-P11-AT", "framework": "Internal policy",
     "text": "EDC administration guide: the EDC records who changed each data point, when, the old and new value, and a reason for change. Periodic audit trail review by data management is planned but not yet part of an approved SOP."},
    {"id": "POL-006", "source_node_id": "CTL-IAM-01", "framework": "Internal policy",
     "text": "Access control policy AC-01: Every user of a clinical system has a unique account federated through single sign-on. Shared or generic accounts are prohibited. Session timeout on clinic workstations is at the discretion of each site."},
    {"id": "POL-007", "source_node_id": "CTL-CONSENT-01", "framework": "Internal policy",
     "text": "eConsent procedure CO-04: Adult participants provide explicit consent electronically. For paediatric studies, site staff record assent; parental identity verification is performed on paper where required by the site."},
    {"id": "POL-008", "source_node_id": "CTL-RA-01", "framework": "Internal policy",
     "text": "Information security programme charter: an enterprise risk analysis of all ePHI systems is performed annually and after significant change. The 2025 assessment was deferred due to the EDC migration."},
]

INSTRUCTIONS = [
    # clinical data protection
    {"id": "INS-CDP-01", "domain": "clinical_data_protection", "title": "Map ePHI safeguards to assets",
     "text": "For each technical safeguard, identify which systems storing or transmitting PHI it covers and flag any PHI-bearing asset without a covering control."},
    {"id": "INS-CDP-02", "domain": "clinical_data_protection", "title": "Addressable is not optional",
     "text": "Treat HIPAA 'addressable' specifications as requiring either implementation or a documented, reasonable alternative; absence of both is a gap."},
    {"id": "INS-CDP-03", "domain": "clinical_data_protection", "title": "Encryption coverage by device class",
     "text": "Assess encryption separately for data at rest in databases, on endpoints and portable devices, and in transit; partial rollout counts as a partial gap."},
    {"id": "INS-CDP-04", "domain": "clinical_data_protection", "title": "Risk analysis currency",
     "text": "Verify the security risk analysis is current (within 12 months) and covers every system in scope; an expired analysis undermines every dependent risk decision."},
    # trial reporting
    {"id": "INS-TRL-01", "domain": "trial_reporting", "title": "Clock-start definitions",
     "text": "When comparing reporting timelines, check when each clock starts (awareness, discovery, first knowledge, classification) - an internal clock that starts later can hide a violation."},
    {"id": "INS-TRL-02", "domain": "trial_reporting", "title": "Strictest-deadline rule",
     "text": "When one procedure serves several jurisdictions, it must meet the strictest applicable deadline; name the binding obligation explicitly."},
    {"id": "INS-TRL-03", "domain": "trial_reporting", "title": "Essential records completeness",
     "text": "Confirm essential trial records and their audit trails are retained and retrievable for the full regulatory retention period."},
    {"id": "INS-TRL-04", "domain": "trial_reporting", "title": "Quality by design",
     "text": "Check that critical-to-quality factors are identified and that monitoring intensity is proportionate to risk to participants and data reliability."},
    # pharmacovigilance
    {"id": "INS-PV-01", "domain": "pharmacovigilance", "title": "Tiered expedited timelines",
     "text": "Verify fatal or life-threatening unexpected reactions follow a 7-day track distinct from the 15-day track for other serious unexpected reactions."},
    {"id": "INS-PV-02", "domain": "pharmacovigilance", "title": "Safety database integrity",
     "text": "Check that the safety database is validated, access-controlled and audit-trailed, since late or altered case data is a patient-safety risk."},
    {"id": "INS-PV-03", "domain": "pharmacovigilance", "title": "Day-zero discipline",
     "text": "Confirm day zero is the first knowledge by any company personnel or partner, including CROs, not the date the safety team logs the case."},
    {"id": "INS-PV-04", "domain": "pharmacovigilance", "title": "Partner case exchange",
     "text": "Check that safety data exchange agreements with CROs and partners specify transfer timelines short enough to meet expedited reporting deadlines."},
    # health privacy
    {"id": "INS-HPR-01", "domain": "health_privacy", "title": "Breach timeline cross-check",
     "text": "Compare the organisation's breach notification commitment against HIPAA (60 days), GDPR (72 hours) and DPDP (72 hours) and report every framework it fails."},
    {"id": "INS-HPR-02", "domain": "health_privacy", "title": "Lawful basis for health data",
     "text": "Confirm a valid special-category condition or explicit consent exists for each health-data processing purpose, including secondary research use."},
    {"id": "INS-HPR-03", "domain": "health_privacy", "title": "Children's data",
     "text": "For paediatric studies, verify verifiable parental consent and the absence of tracking or behavioural monitoring of children."},
    {"id": "INS-HPR-04", "domain": "health_privacy", "title": "Access request service levels",
     "text": "Check access-request service levels against HIPAA (30 days), GDPR (one month) and DPDP; a single queue must meet the shortest."},
    {"id": "INS-HPR-05", "domain": "health_privacy", "title": "DPIA before high-risk processing",
     "text": "Large-scale processing of health data in trials requires a DPIA before processing begins; a template alone is not evidence."},
    # quality systems (Part 11 / GxP)
    {"id": "INS-QMS-01", "domain": "quality_systems", "title": "Audit trail review",
     "text": "An audit trail that exists but is never reviewed is a partial control; look for documented, periodic review and evidence of it."},
    {"id": "INS-QMS-02", "domain": "quality_systems", "title": "Validation after change",
     "text": "Systems must be revalidated after significant upgrades; an in-progress revalidation means the current production version is unvalidated."},
    {"id": "INS-QMS-03", "domain": "quality_systems", "title": "Evidence or it didn't happen",
     "text": "Treat an implemented control with no collected evidence as an audit finding; name the evidence an inspector would expect."},
    {"id": "INS-QMS-04", "domain": "quality_systems", "title": "E-signature linkage",
     "text": "Verify electronic signatures use two components, show name, date/time and meaning, and are linked to their records so they cannot be copied."},
]
